on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: erlef/setup-beam@v1.15.0
        with:
          otp-version: "25.1.2"
          rebar3-version: "3.20.0"
      - run: rebar3 ct
      - run: cat _build/test/logs/last/example_cth.log || echo 'no example_cth.log'
      - run: cat _build/test/logs/last/example_cth2.log || echo 'no example_cth2.log'
